{
    'name': 'Goliatt - Contabilidad',
    'version': '19.0.1.0.0',
    'summary': 'Módulo de contabilidad Goliatt con todas las funcionalidades contables colombianas',
    'category': 'Accounting',
    'author': 'Goliatt',
    'depends': [
        'account',
        'analytic',
        'account_payment',
        'co_accounting_extended',
        'co_bank_reconciliation',
        'co_budget',
        'co_fixed_assets',
        'co_exogena',
        'account_ledger_report',
        'account_balance_sheet',
        'account_profit_loss',
        'account_general_ledger',
        'account_aged_receivable',
        'account_aged_payable',
        'account_cash_flow',
    ],
    'data': [
        'security/goliatt_security.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'sequence': 10,
}
