{
    'name': 'Contabilidad Colombiana Extendida',
    'version': '19.0.2.0.0',
    'summary': 'Centros de costo, códigos de ítem, unidades de negocio, reglas de contabilización automática, cierre anual y conceptos formulados para contabilidad colombiana',
    'category': 'Accounting',
    'author': 'Custom',
    'depends': ['account', 'analytic', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/co_cost_center_views.xml',
        'views/co_item_code_views.xml',
        'views/co_business_unit_views.xml',
        'views/account_account_views.xml',
        'views/account_analytic_account_views.xml',
        'views/co_auto_posting_rule_views.xml',
        'views/co_accounting_concept_views.xml',
        'views/co_formulated_concept_views.xml',
        'views/account_move_line_views.xml',
        'report/account_move_report.xml',
        'wizard/co_year_close_wizard_views.xml',
        'wizard/account_move_export_wizard_views.xml',
        'wizard/account_move_import_wizard_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
